// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (title, type, location_id, start_date, start_time, end_date, end_time, all_day,
                    source_description, source_url, note, effective_start, effective_end)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, title, type, location_id, start_date, start_time, end_date, end_time, all_day,
          source_description, source_url, note, effective_start, effective_end
`

type CreateEventParams struct {
	Title             string
	Type              string
	LocationID        pgtype.UUID
	StartDate         pgtype.Date
	StartTime         pgtype.Time
	EndDate           pgtype.Date
	EndTime           pgtype.Time
	AllDay            bool
	SourceDescription string
	SourceUrl         pgtype.Text
	Note              pgtype.Text
	EffectiveStart    pgtype.Timestamptz
	EffectiveEnd      pgtype.Timestamptz
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Title,
		arg.Type,
		arg.LocationID,
		arg.StartDate,
		arg.StartTime,
		arg.EndDate,
		arg.EndTime,
		arg.AllDay,
		arg.SourceDescription,
		arg.SourceUrl,
		arg.Note,
		arg.EffectiveStart,
		arg.EffectiveEnd,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.LocationID,
		&i.StartDate,
		&i.StartTime,
		&i.EndDate,
		&i.EndTime,
		&i.AllDay,
		&i.SourceDescription,
		&i.SourceUrl,
		&i.Note,
		&i.EffectiveStart,
		&i.EffectiveEnd,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, title, type, location_id, start_date, start_time, end_date, end_time, all_day,
       source_description, source_url, note, effective_start, effective_end
FROM events
WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.LocationID,
		&i.StartDate,
		&i.StartTime,
		&i.EndDate,
		&i.EndTime,
		&i.AllDay,
		&i.SourceDescription,
		&i.SourceUrl,
		&i.Note,
		&i.EffectiveStart,
		&i.EffectiveEnd,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many

SELECT id, title, type, location_id, start_date, start_time, end_date, end_time, all_day,
       source_description, source_url, note, effective_start, effective_end
FROM events
`

// Plain CRUD only: sorting, validation and the effective period live in the
// core (AD-2).
func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.LocationID,
			&i.StartDate,
			&i.StartTime,
			&i.EndDate,
			&i.EndTime,
			&i.AllDay,
			&i.SourceDescription,
			&i.SourceUrl,
			&i.Note,
			&i.EffectiveStart,
			&i.EffectiveEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET title = $2, type = $3, location_id = $4, start_date = $5, start_time = $6,
    end_date = $7, end_time = $8, all_day = $9, source_description = $10,
    source_url = $11, note = $12, effective_start = $13, effective_end = $14
WHERE id = $1
RETURNING id, title, type, location_id, start_date, start_time, end_date, end_time, all_day,
          source_description, source_url, note, effective_start, effective_end
`

type UpdateEventParams struct {
	ID                pgtype.UUID
	Title             string
	Type              string
	LocationID        pgtype.UUID
	StartDate         pgtype.Date
	StartTime         pgtype.Time
	EndDate           pgtype.Date
	EndTime           pgtype.Time
	AllDay            bool
	SourceDescription string
	SourceUrl         pgtype.Text
	Note              pgtype.Text
	EffectiveStart    pgtype.Timestamptz
	EffectiveEnd      pgtype.Timestamptz
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Title,
		arg.Type,
		arg.LocationID,
		arg.StartDate,
		arg.StartTime,
		arg.EndDate,
		arg.EndTime,
		arg.AllDay,
		arg.SourceDescription,
		arg.SourceUrl,
		arg.Note,
		arg.EffectiveStart,
		arg.EffectiveEnd,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.LocationID,
		&i.StartDate,
		&i.StartTime,
		&i.EndDate,
		&i.EndTime,
		&i.AllDay,
		&i.SourceDescription,
		&i.SourceUrl,
		&i.Note,
		&i.EffectiveStart,
		&i.EffectiveEnd,
	)
	return i, err
}

const updateEventPeriod = `-- name: UpdateEventPeriod :execrows
UPDATE events
SET effective_start = $2, effective_end = $3
WHERE id = $1
`

type UpdateEventPeriodParams struct {
	ID             pgtype.UUID
	EffectiveStart pgtype.Timestamptz
	EffectiveEnd   pgtype.Timestamptz
}

func (q *Queries) UpdateEventPeriod(ctx context.Context, arg UpdateEventPeriodParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEventPeriod, arg.ID, arg.EffectiveStart, arg.EffectiveEnd)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
