// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEventsByLocation = `-- name: CountEventsByLocation :one
SELECT count(*)
FROM events
WHERE location_id = $1
`

func (q *Queries) CountEventsByLocation(ctx context.Context, locationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsByLocation, locationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (title, title_key, type, location_id, start_date, start_time, end_date, end_time, all_day,
                    source_description, source_url, note, effective_start, effective_end)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, title, type, location_id, start_date, start_time, end_date, end_time, all_day,
          source_description, source_url, note, effective_start, effective_end, title_key, import_key
`

type CreateEventParams struct {
	Title             string
	TitleKey          string
	Type              string
	LocationID        pgtype.UUID
	StartDate         pgtype.Date
	StartTime         pgtype.Time
	EndDate           pgtype.Date
	EndTime           pgtype.Time
	AllDay            bool
	SourceDescription string
	SourceUrl         pgtype.Text
	Note              pgtype.Text
	EffectiveStart    pgtype.Timestamptz
	EffectiveEnd      pgtype.Timestamptz
}

type CreateEventRow struct {
	ID                pgtype.UUID
	Title             string
	Type              string
	LocationID        pgtype.UUID
	StartDate         pgtype.Date
	StartTime         pgtype.Time
	EndDate           pgtype.Date
	EndTime           pgtype.Time
	AllDay            bool
	SourceDescription string
	SourceUrl         pgtype.Text
	Note              pgtype.Text
	EffectiveStart    pgtype.Timestamptz
	EffectiveEnd      pgtype.Timestamptz
	TitleKey          string
	ImportKey         pgtype.Text
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (CreateEventRow, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Title,
		arg.TitleKey,
		arg.Type,
		arg.LocationID,
		arg.StartDate,
		arg.StartTime,
		arg.EndDate,
		arg.EndTime,
		arg.AllDay,
		arg.SourceDescription,
		arg.SourceUrl,
		arg.Note,
		arg.EffectiveStart,
		arg.EffectiveEnd,
	)
	var i CreateEventRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.LocationID,
		&i.StartDate,
		&i.StartTime,
		&i.EndDate,
		&i.EndTime,
		&i.AllDay,
		&i.SourceDescription,
		&i.SourceUrl,
		&i.Note,
		&i.EffectiveStart,
		&i.EffectiveEnd,
		&i.TitleKey,
		&i.ImportKey,
	)
	return i, err
}

const createTimetableEntry = `-- name: CreateTimetableEntry :one
INSERT INTO timetable_entries (event_id, description, date, start_time, end_time)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, event_id, description, date, start_time, end_time
`

type CreateTimetableEntryParams struct {
	EventID     pgtype.UUID
	Description string
	Date        pgtype.Date
	StartTime   pgtype.Time
	EndTime     pgtype.Time
}

func (q *Queries) CreateTimetableEntry(ctx context.Context, arg CreateTimetableEntryParams) (TimetableEntry, error) {
	row := q.db.QueryRow(ctx, createTimetableEntry,
		arg.EventID,
		arg.Description,
		arg.Date,
		arg.StartTime,
		arg.EndTime,
	)
	var i TimetableEntry
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Description,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :execrows
DELETE FROM events
WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEvent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTimetableEntriesOfEvent = `-- name: DeleteTimetableEntriesOfEvent :exec
DELETE FROM timetable_entries
WHERE event_id = $1
`

func (q *Queries) DeleteTimetableEntriesOfEvent(ctx context.Context, eventID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTimetableEntriesOfEvent, eventID)
	return err
}

const findEventsByDuplicateKey = `-- name: FindEventsByDuplicateKey :many
SELECT id, title, type, location_id, start_date, start_time, end_date, end_time, all_day,
       source_description, source_url, note, effective_start, effective_end, title_key, import_key
FROM events
WHERE title_key = $1 AND start_date = $2 AND location_id = $3
`

type FindEventsByDuplicateKeyParams struct {
	TitleKey   string
	StartDate  pgtype.Date
	LocationID pgtype.UUID
}

type FindEventsByDuplicateKeyRow struct {
	ID                pgtype.UUID
	Title             string
	Type              string
	LocationID        pgtype.UUID
	StartDate         pgtype.Date
	StartTime         pgtype.Time
	EndDate           pgtype.Date
	EndTime           pgtype.Time
	AllDay            bool
	SourceDescription string
	SourceUrl         pgtype.Text
	Note              pgtype.Text
	EffectiveStart    pgtype.Timestamptz
	EffectiveEnd      pgtype.Timestamptz
	TitleKey          string
	ImportKey         pgtype.Text
}

func (q *Queries) FindEventsByDuplicateKey(ctx context.Context, arg FindEventsByDuplicateKeyParams) ([]FindEventsByDuplicateKeyRow, error) {
	rows, err := q.db.Query(ctx, findEventsByDuplicateKey, arg.TitleKey, arg.StartDate, arg.LocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindEventsByDuplicateKeyRow
	for rows.Next() {
		var i FindEventsByDuplicateKeyRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.LocationID,
			&i.StartDate,
			&i.StartTime,
			&i.EndDate,
			&i.EndTime,
			&i.AllDay,
			&i.SourceDescription,
			&i.SourceUrl,
			&i.Note,
			&i.EffectiveStart,
			&i.EffectiveEnd,
			&i.TitleKey,
			&i.ImportKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvent = `-- name: GetEvent :one
SELECT id, title, type, location_id, start_date, start_time, end_date, end_time, all_day,
       source_description, source_url, note, effective_start, effective_end, title_key, import_key
FROM events
WHERE id = $1
`

type GetEventRow struct {
	ID                pgtype.UUID
	Title             string
	Type              string
	LocationID        pgtype.UUID
	StartDate         pgtype.Date
	StartTime         pgtype.Time
	EndDate           pgtype.Date
	EndTime           pgtype.Time
	AllDay            bool
	SourceDescription string
	SourceUrl         pgtype.Text
	Note              pgtype.Text
	EffectiveStart    pgtype.Timestamptz
	EffectiveEnd      pgtype.Timestamptz
	TitleKey          string
	ImportKey         pgtype.Text
}

func (q *Queries) GetEvent(ctx context.Context, id pgtype.UUID) (GetEventRow, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i GetEventRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.LocationID,
		&i.StartDate,
		&i.StartTime,
		&i.EndDate,
		&i.EndTime,
		&i.AllDay,
		&i.SourceDescription,
		&i.SourceUrl,
		&i.Note,
		&i.EffectiveStart,
		&i.EffectiveEnd,
		&i.TitleKey,
		&i.ImportKey,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many

SELECT id, title, type, location_id, start_date, start_time, end_date, end_time, all_day,
       source_description, source_url, note, effective_start, effective_end, title_key, import_key
FROM events
`

type ListEventsRow struct {
	ID                pgtype.UUID
	Title             string
	Type              string
	LocationID        pgtype.UUID
	StartDate         pgtype.Date
	StartTime         pgtype.Time
	EndDate           pgtype.Date
	EndTime           pgtype.Time
	AllDay            bool
	SourceDescription string
	SourceUrl         pgtype.Text
	Note              pgtype.Text
	EffectiveStart    pgtype.Timestamptz
	EffectiveEnd      pgtype.Timestamptz
	TitleKey          string
	ImportKey         pgtype.Text
}

// Plain CRUD only: sorting, validation and the effective period live in the
// core (AD-2).
func (q *Queries) ListEvents(ctx context.Context) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsRow
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.LocationID,
			&i.StartDate,
			&i.StartTime,
			&i.EndDate,
			&i.EndTime,
			&i.AllDay,
			&i.SourceDescription,
			&i.SourceUrl,
			&i.Note,
			&i.EffectiveStart,
			&i.EffectiveEnd,
			&i.TitleKey,
			&i.ImportKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsOverlapping = `-- name: ListEventsOverlapping :many
SELECT id, title, type, location_id, start_date, start_time, end_date, end_time, all_day,
       source_description, source_url, note, effective_start, effective_end, title_key, import_key
FROM events
WHERE ($1::timestamptz IS NULL OR effective_end > $1)
  AND ($2::timestamptz IS NULL OR effective_start < $2)
`

type ListEventsOverlappingParams struct {
	Lo pgtype.Timestamptz
	Hi pgtype.Timestamptz
}

type ListEventsOverlappingRow struct {
	ID                pgtype.UUID
	Title             string
	Type              string
	LocationID        pgtype.UUID
	StartDate         pgtype.Date
	StartTime         pgtype.Time
	EndDate           pgtype.Date
	EndTime           pgtype.Time
	AllDay            bool
	SourceDescription string
	SourceUrl         pgtype.Text
	Note              pgtype.Text
	EffectiveStart    pgtype.Timestamptz
	EffectiveEnd      pgtype.Timestamptz
	TitleKey          string
	ImportKey         pgtype.Text
}

// The one filter predicate of AD-16 on the stored effective period; a NULL
// lo leaves the period open at the start, a NULL hi open-ended. The core
// passes lo and hi as parameters.
func (q *Queries) ListEventsOverlapping(ctx context.Context, arg ListEventsOverlappingParams) ([]ListEventsOverlappingRow, error) {
	rows, err := q.db.Query(ctx, listEventsOverlapping, arg.Lo, arg.Hi)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsOverlappingRow
	for rows.Next() {
		var i ListEventsOverlappingRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.LocationID,
			&i.StartDate,
			&i.StartTime,
			&i.EndDate,
			&i.EndTime,
			&i.AllDay,
			&i.SourceDescription,
			&i.SourceUrl,
			&i.Note,
			&i.EffectiveStart,
			&i.EffectiveEnd,
			&i.TitleKey,
			&i.ImportKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimetableEntries = `-- name: ListTimetableEntries :many
SELECT id, event_id, description, date, start_time, end_time
FROM timetable_entries
`

func (q *Queries) ListTimetableEntries(ctx context.Context) ([]TimetableEntry, error) {
	rows, err := q.db.Query(ctx, listTimetableEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimetableEntry
	for rows.Next() {
		var i TimetableEntry
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Description,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimetableEntriesOfEvent = `-- name: ListTimetableEntriesOfEvent :many
SELECT id, event_id, description, date, start_time, end_time
FROM timetable_entries
WHERE event_id = $1
`

func (q *Queries) ListTimetableEntriesOfEvent(ctx context.Context, eventID pgtype.UUID) ([]TimetableEntry, error) {
	rows, err := q.db.Query(ctx, listTimetableEntriesOfEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimetableEntry
	for rows.Next() {
		var i TimetableEntry
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Description,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimetableEntriesOfEvents = `-- name: ListTimetableEntriesOfEvents :many
SELECT id, event_id, description, date, start_time, end_time
FROM timetable_entries
WHERE event_id = ANY($1::uuid[])
`

func (q *Queries) ListTimetableEntriesOfEvents(ctx context.Context, eventIds []pgtype.UUID) ([]TimetableEntry, error) {
	rows, err := q.db.Query(ctx, listTimetableEntriesOfEvents, eventIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimetableEntry
	for rows.Next() {
		var i TimetableEntry
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Description,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventsArchived = `-- name: MarkEventsArchived :execrows
UPDATE events
SET archived_at = $1
WHERE effective_end <= $1 AND archived_at IS NULL
`

// One statement, so an event that a concurrent save makes active again is
// checked against its new effective_end and stays unmarked. The core passes
// now as a parameter (AD-2).
func (q *Queries) MarkEventsArchived(ctx context.Context, now pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, markEventsArchived, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET title = $2, title_key = $3, type = $4, location_id = $5, start_date = $6, start_time = $7,
    end_date = $8, end_time = $9, all_day = $10, source_description = $11,
    source_url = $12, note = $13, effective_start = $14, effective_end = $15,
    archived_at = NULL
WHERE id = $1
RETURNING id, title, type, location_id, start_date, start_time, end_date, end_time, all_day,
          source_description, source_url, note, effective_start, effective_end, title_key, import_key
`

type UpdateEventParams struct {
	ID                pgtype.UUID
	Title             string
	TitleKey          string
	Type              string
	LocationID        pgtype.UUID
	StartDate         pgtype.Date
	StartTime         pgtype.Time
	EndDate           pgtype.Date
	EndTime           pgtype.Time
	AllDay            bool
	SourceDescription string
	SourceUrl         pgtype.Text
	Note              pgtype.Text
	EffectiveStart    pgtype.Timestamptz
	EffectiveEnd      pgtype.Timestamptz
}

type UpdateEventRow struct {
	ID                pgtype.UUID
	Title             string
	Type              string
	LocationID        pgtype.UUID
	StartDate         pgtype.Date
	StartTime         pgtype.Time
	EndDate           pgtype.Date
	EndTime           pgtype.Time
	AllDay            bool
	SourceDescription string
	SourceUrl         pgtype.Text
	Note              pgtype.Text
	EffectiveStart    pgtype.Timestamptz
	EffectiveEnd      pgtype.Timestamptz
	TitleKey          string
	ImportKey         pgtype.Text
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (UpdateEventRow, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Title,
		arg.TitleKey,
		arg.Type,
		arg.LocationID,
		arg.StartDate,
		arg.StartTime,
		arg.EndDate,
		arg.EndTime,
		arg.AllDay,
		arg.SourceDescription,
		arg.SourceUrl,
		arg.Note,
		arg.EffectiveStart,
		arg.EffectiveEnd,
	)
	var i UpdateEventRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.LocationID,
		&i.StartDate,
		&i.StartTime,
		&i.EndDate,
		&i.EndTime,
		&i.AllDay,
		&i.SourceDescription,
		&i.SourceUrl,
		&i.Note,
		&i.EffectiveStart,
		&i.EffectiveEnd,
		&i.TitleKey,
		&i.ImportKey,
	)
	return i, err
}

const updateEventDerived = `-- name: UpdateEventDerived :execrows
UPDATE events
SET effective_start = $2, effective_end = $3, title_key = $4, archived_at = NULL
WHERE id = $1
`

type UpdateEventDerivedParams struct {
	ID             pgtype.UUID
	EffectiveStart pgtype.Timestamptz
	EffectiveEnd   pgtype.Timestamptz
	TitleKey       string
}

func (q *Queries) UpdateEventDerived(ctx context.Context, arg UpdateEventDerivedParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEventDerived,
		arg.ID,
		arg.EffectiveStart,
		arg.EffectiveEnd,
		arg.TitleKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEventImportKey = `-- name: UpdateEventImportKey :execrows
UPDATE events
SET import_key = $2
WHERE id = $1
`

type UpdateEventImportKeyParams struct {
	ID        pgtype.UUID
	ImportKey pgtype.Text
}

// Only the import commit sets the import key (Story 3.3).
func (q *Queries) UpdateEventImportKey(ctx context.Context, arg UpdateEventImportKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEventImportKey, arg.ID, arg.ImportKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
