// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (name, name_key, street, postal_code, city, latitude, longitude, precision, note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, name_key, street, postal_code, city, latitude, longitude, precision, note
`

type CreateLocationParams struct {
	Name       string
	NameKey    string
	Street     string
	PostalCode string
	City       string
	Latitude   float64
	Longitude  float64
	Precision  string
	Note       pgtype.Text
}

type CreateLocationRow struct {
	ID         pgtype.UUID
	Name       string
	NameKey    string
	Street     string
	PostalCode string
	City       string
	Latitude   float64
	Longitude  float64
	Precision  string
	Note       pgtype.Text
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (CreateLocationRow, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.Name,
		arg.NameKey,
		arg.Street,
		arg.PostalCode,
		arg.City,
		arg.Latitude,
		arg.Longitude,
		arg.Precision,
		arg.Note,
	)
	var i CreateLocationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameKey,
		&i.Street,
		&i.PostalCode,
		&i.City,
		&i.Latitude,
		&i.Longitude,
		&i.Precision,
		&i.Note,
	)
	return i, err
}

const deleteLocation = `-- name: DeleteLocation :execrows
DELETE FROM locations
WHERE id = $1
`

func (q *Queries) DeleteLocation(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLocation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findLocationByNameKey = `-- name: FindLocationByNameKey :one
SELECT id, name, name_key, street, postal_code, city, latitude, longitude, precision, note
FROM locations
WHERE name_key = $1
`

type FindLocationByNameKeyRow struct {
	ID         pgtype.UUID
	Name       string
	NameKey    string
	Street     string
	PostalCode string
	City       string
	Latitude   float64
	Longitude  float64
	Precision  string
	Note       pgtype.Text
}

func (q *Queries) FindLocationByNameKey(ctx context.Context, nameKey string) (FindLocationByNameKeyRow, error) {
	row := q.db.QueryRow(ctx, findLocationByNameKey, nameKey)
	var i FindLocationByNameKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameKey,
		&i.Street,
		&i.PostalCode,
		&i.City,
		&i.Latitude,
		&i.Longitude,
		&i.Precision,
		&i.Note,
	)
	return i, err
}

const getLocation = `-- name: GetLocation :one
SELECT id, name, name_key, street, postal_code, city, latitude, longitude, precision, note
FROM locations
WHERE id = $1
`

type GetLocationRow struct {
	ID         pgtype.UUID
	Name       string
	NameKey    string
	Street     string
	PostalCode string
	City       string
	Latitude   float64
	Longitude  float64
	Precision  string
	Note       pgtype.Text
}

func (q *Queries) GetLocation(ctx context.Context, id pgtype.UUID) (GetLocationRow, error) {
	row := q.db.QueryRow(ctx, getLocation, id)
	var i GetLocationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameKey,
		&i.Street,
		&i.PostalCode,
		&i.City,
		&i.Latitude,
		&i.Longitude,
		&i.Precision,
		&i.Note,
	)
	return i, err
}

const listLocations = `-- name: ListLocations :many

SELECT id, name, name_key, street, postal_code, city, latitude, longitude, precision, note
FROM locations
`

type ListLocationsRow struct {
	ID         pgtype.UUID
	Name       string
	NameKey    string
	Street     string
	PostalCode string
	City       string
	Latitude   float64
	Longitude  float64
	Precision  string
	Note       pgtype.Text
}

// Plain CRUD only: sorting, normalization and validation live in the core.
// The column address is left over from before Story 1.12 and is neither read
// nor written (AD-17), so every query names its columns.
func (q *Queries) ListLocations(ctx context.Context) ([]ListLocationsRow, error) {
	rows, err := q.db.Query(ctx, listLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocationsRow
	for rows.Next() {
		var i ListLocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameKey,
			&i.Street,
			&i.PostalCode,
			&i.City,
			&i.Latitude,
			&i.Longitude,
			&i.Precision,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations
SET name = $2, name_key = $3, street = $4, postal_code = $5, city = $6,
    latitude = $7, longitude = $8, precision = $9, note = $10
WHERE id = $1
RETURNING id, name, name_key, street, postal_code, city, latitude, longitude, precision, note
`

type UpdateLocationParams struct {
	ID         pgtype.UUID
	Name       string
	NameKey    string
	Street     string
	PostalCode string
	City       string
	Latitude   float64
	Longitude  float64
	Precision  string
	Note       pgtype.Text
}

type UpdateLocationRow struct {
	ID         pgtype.UUID
	Name       string
	NameKey    string
	Street     string
	PostalCode string
	City       string
	Latitude   float64
	Longitude  float64
	Precision  string
	Note       pgtype.Text
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (UpdateLocationRow, error) {
	row := q.db.QueryRow(ctx, updateLocation,
		arg.ID,
		arg.Name,
		arg.NameKey,
		arg.Street,
		arg.PostalCode,
		arg.City,
		arg.Latitude,
		arg.Longitude,
		arg.Precision,
		arg.Note,
	)
	var i UpdateLocationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameKey,
		&i.Street,
		&i.PostalCode,
		&i.City,
		&i.Latitude,
		&i.Longitude,
		&i.Precision,
		&i.Note,
	)
	return i, err
}

const updateLocationNameKey = `-- name: UpdateLocationNameKey :execrows
UPDATE locations
SET name_key = $2
WHERE id = $1
`

type UpdateLocationNameKeyParams struct {
	ID      pgtype.UUID
	NameKey string
}

func (q *Queries) UpdateLocationNameKey(ctx context.Context, arg UpdateLocationNameKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLocationNameKey, arg.ID, arg.NameKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
