// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (name, name_key, address, latitude, longitude, precision, note)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, name_key, address, latitude, longitude, precision, note
`

type CreateLocationParams struct {
	Name      string
	NameKey   string
	Address   string
	Latitude  float64
	Longitude float64
	Precision string
	Note      pgtype.Text
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.Name,
		arg.NameKey,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.Precision,
		arg.Note,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameKey,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Precision,
		&i.Note,
	)
	return i, err
}

const findLocationByNameKey = `-- name: FindLocationByNameKey :one
SELECT id, name, name_key, address, latitude, longitude, precision, note
FROM locations
WHERE name_key = $1
`

func (q *Queries) FindLocationByNameKey(ctx context.Context, nameKey string) (Location, error) {
	row := q.db.QueryRow(ctx, findLocationByNameKey, nameKey)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameKey,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Precision,
		&i.Note,
	)
	return i, err
}

const getLocation = `-- name: GetLocation :one
SELECT id, name, name_key, address, latitude, longitude, precision, note
FROM locations
WHERE id = $1
`

func (q *Queries) GetLocation(ctx context.Context, id pgtype.UUID) (Location, error) {
	row := q.db.QueryRow(ctx, getLocation, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameKey,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Precision,
		&i.Note,
	)
	return i, err
}

const listLocations = `-- name: ListLocations :many

SELECT id, name, name_key, address, latitude, longitude, precision, note
FROM locations
`

// Plain CRUD only: sorting, normalization and validation live in the core.
func (q *Queries) ListLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameKey,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Precision,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations
SET name = $2, name_key = $3, address = $4, latitude = $5, longitude = $6, precision = $7, note = $8
WHERE id = $1
RETURNING id, name, name_key, address, latitude, longitude, precision, note
`

type UpdateLocationParams struct {
	ID        pgtype.UUID
	Name      string
	NameKey   string
	Address   string
	Latitude  float64
	Longitude float64
	Precision string
	Note      pgtype.Text
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateLocation,
		arg.ID,
		arg.Name,
		arg.NameKey,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.Precision,
		arg.Note,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameKey,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Precision,
		&i.Note,
	)
	return i, err
}
