// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locks.sql

package db

import (
	"context"
)

const takeWriteLock = `-- name: TakeWriteLock :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

// Waits for the transaction-level advisory lock with the given key and
// holds it until the transaction ends, so write transactions run one after
// the other.
func (q *Queries) TakeWriteLock(ctx context.Context, lockKey int64) error {
	_, err := q.db.Exec(ctx, takeWriteLock, lockKey)
	return err
}
