// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID                pgtype.UUID
	Title             string
	Type              string
	LocationID        pgtype.UUID
	StartDate         pgtype.Date
	StartTime         pgtype.Time
	EndDate           pgtype.Date
	EndTime           pgtype.Time
	AllDay            bool
	SourceDescription string
	SourceUrl         pgtype.Text
	Note              pgtype.Text
	EffectiveStart    pgtype.Timestamptz
	EffectiveEnd      pgtype.Timestamptz
}

type Location struct {
	ID         pgtype.UUID
	Name       string
	NameKey    string
	Address    pgtype.Text
	Latitude   float64
	Longitude  float64
	Precision  string
	Note       pgtype.Text
	Street     string
	PostalCode string
	City       string
}

type TimetableEntry struct {
	ID          pgtype.UUID
	EventID     pgtype.UUID
	Description string
	Date        pgtype.Date
	StartTime   pgtype.Time
	EndTime     pgtype.Time
}
