// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Location struct {
	ID         pgtype.UUID
	Name       string
	NameKey    string
	Address    pgtype.Text
	Latitude   float64
	Longitude  float64
	Precision  string
	Note       pgtype.Text
	Street     string
	PostalCode string
	City       string
}
