// Package lateheader has an untested file whose generated header follows
// the package clause, so it does not mark the file as generated.
package lateheader

// Code generated by nobody. DO NOT EDIT.

// Triple returns three times n; no test calls it.
func Triple(n int) int {
	return 3 * n
}
