//go:build go1.22

// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
)

// Defines values for EventType.
const (
	EventTypeClub     EventType = "club"
	EventTypeCulture  EventType = "culture"
	EventTypeFestival EventType = "festival"
	EventTypeMarket   EventType = "market"
	EventTypeOther    EventType = "other"
	EventTypePolitics EventType = "politics"
	EventTypeSports   EventType = "sports"
)

// Valid indicates whether the value is a known member of the EventType enum.
func (e EventType) Valid() bool {
	switch e {
	case EventTypeClub:
		return true
	case EventTypeCulture:
		return true
	case EventTypeFestival:
		return true
	case EventTypeMarket:
		return true
	case EventTypeOther:
		return true
	case EventTypePolitics:
		return true
	case EventTypeSports:
		return true
	default:
		return false
	}
}

// Defines values for LocationPrecision.
const (
	LocationPrecisionArea     LocationPrecision = "area"
	LocationPrecisionBuilding LocationPrecision = "building"
	LocationPrecisionDistrict LocationPrecision = "district"
	LocationPrecisionStreet   LocationPrecision = "street"
)

// Valid indicates whether the value is a known member of the LocationPrecision enum.
func (e LocationPrecision) Valid() bool {
	switch e {
	case LocationPrecisionArea:
		return true
	case LocationPrecisionBuilding:
		return true
	case LocationPrecisionDistrict:
		return true
	case LocationPrecisionStreet:
		return true
	default:
		return false
	}
}

// Defines values for TimePrecision.
const (
	TimePrecisionAllDay   TimePrecision = "allDay"
	TimePrecisionDateOnly TimePrecision = "dateOnly"
	TimePrecisionExact    TimePrecision = "exact"
)

// Valid indicates whether the value is a known member of the TimePrecision enum.
func (e TimePrecision) Valid() bool {
	switch e {
	case TimePrecisionAllDay:
		return true
	case TimePrecisionDateOnly:
		return true
	case TimePrecisionExact:
		return true
	default:
		return false
	}
}

// EventType Classifies an event for filters and map icons. Codes:
// `festival` (festival or Kirchweih fair), `market` (market),
// `culture` (culture or stage performance), `politics` (politics or
// council meeting), `club` (club or meetup), `sports` (sports),
// `other` (anything else).
type EventType string

// EventTypeEntry An event type code with its German label.
type EventTypeEntry struct {
	// Code Classifies an event for filters and map icons. Codes:
	// `festival` (festival or Kirchweih fair), `market` (market),
	// `culture` (culture or stage performance), `politics` (politics or
	// council meeting), `club` (club or meetup), `sports` (sports),
	// `other` (anything else).
	Code EventType `json:"code"`

	// Label German display name of the event type.
	Label string `json:"label"`
}

// EventTypeList List envelope (KON-8) around all event types.
type EventTypeList struct {
	// Data Every event type, in display order.
	Data []EventTypeEntry `json:"data"`
}

// LocationPrecision How exactly the coordinates of a location mark the place.
// `building`: a single building or entrance.
// `street`: a square or street.
// `area`: an area such as a park or fairground.
// `district`: only the district of Zirndorf is known.
type LocationPrecision string

// Problem Error response according to RFC 9457 (Problem Details), delivered as
// `application/problem+json`.
type Problem struct {
	// Detail English explanation of this occurrence of the problem.
	Detail string `json:"detail"`

	// Status HTTP status code of the response.
	Status int `json:"status"`

	// Title Short English summary, the reason phrase of the HTTP status.
	Title string `json:"title"`

	// Type URI reference identifying the problem type. The API uses
	// `about:blank`, so the HTTP status alone names the problem.
	Type string `json:"type"`
}

// TimePrecision How exactly the start or end of an event is known.
// `exact`: date and local time are known.
// `dateOnly`: only the date is known, the time is unknown.
// `allDay`: the event lasts the whole day, it has no time.
type TimePrecision string

// InternalServerError Error response according to RFC 9457 (Problem Details), delivered as
// `application/problem+json`.
type InternalServerError = Problem

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListEventTypes List the event types
	// (GET /event-types)
	ListEventTypes(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListEventTypes operation middleware
func (siw *ServerInterfaceWrapper) ListEventTypes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEventTypes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/event-types", wrapper.ListEventTypes)

	return m
}

type InternalServerErrorApplicationProblemPlusJSONResponse Problem

type ListEventTypesRequestObject struct {
}

type ListEventTypesResponseObject interface {
	VisitListEventTypesResponse(w http.ResponseWriter) error
}

type ListEventTypes200JSONResponse EventTypeList

func (response ListEventTypes200JSONResponse) VisitListEventTypesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListEventTypes500ApplicationProblemPlusJSONResponse struct {
	InternalServerErrorApplicationProblemPlusJSONResponse
}

func (response ListEventTypes500ApplicationProblemPlusJSONResponse) VisitListEventTypesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListEventTypes List the event types
	// (GET /event-types)
	ListEventTypes(ctx context.Context, request ListEventTypesRequestObject) (ListEventTypesResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListEventTypes operation middleware
func (sh *strictHandler) ListEventTypes(w http.ResponseWriter, r *http.Request) {
	var request ListEventTypesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListEventTypes(ctx, request.(ListEventTypesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListEventTypes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListEventTypesResponseObject); ok {
		if err := validResponse.VisitListEventTypesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
